/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, RequestLog as PrismaRequestLog } from "@prisma/client";

export class RequestLogServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.RequestLogCountArgs, "select">
  ): Promise<number> {
    return this.prisma.requestLog.count(args);
  }

  async requestLogs(
    args: Prisma.RequestLogFindManyArgs
  ): Promise<PrismaRequestLog[]> {
    return this.prisma.requestLog.findMany(args);
  }
  async requestLog(
    args: Prisma.RequestLogFindUniqueArgs
  ): Promise<PrismaRequestLog | null> {
    return this.prisma.requestLog.findUnique(args);
  }
  async createRequestLog(
    args: Prisma.RequestLogCreateArgs
  ): Promise<PrismaRequestLog> {
    return this.prisma.requestLog.create(args);
  }
  async updateRequestLog(
    args: Prisma.RequestLogUpdateArgs
  ): Promise<PrismaRequestLog> {
    return this.prisma.requestLog.update(args);
  }
  async deleteRequestLog(
    args: Prisma.RequestLogDeleteArgs
  ): Promise<PrismaRequestLog> {
    return this.prisma.requestLog.delete(args);
  }
}
